linters:
  Rails/OutputSafety:
    Enabled: false
  LineLength:
    enabled: false
  AccessibleAlt:
    enabled: true
  NoEmptyElements:
    enabled: false

include_linters:
  - Linter::LineLength
  - Linter::AccessibleAlt
  - Linter::NoEmptyElements